name: ci
on:
  push:
    branches:
      - main

jobs:
  asciidoctor_job:
    runs-on: ubuntu-18.04
    name: Build AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor src/README.adoc -o build/index.html" 
    - name: Commit updated files
      run: |
          git add build/
          git config user.name cnp-survey-runner
          git config user.email cnp-survey-runner@example.com
          git commit -m "test"
          git push origin main
    - name: move deploy files
      run: |
        sudo mv build/* docs/
        ls docs
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages