name: ci
on:
  push:
    branches:
      - main

jobs:
  asciidoctor_job:
    runs-on: ubuntu-18.04
    name: Build AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor test.adoc -o docs/test.html" 
    # - name: Save AsciiDoc step
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: Output-document
    #     path: public/test.html