name: ci
on:
  push:

jobs:
  asciidoctor_job:
    runs-on: self-hosted
    name: build asciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor src/README.adoc -o docs/test.html" 
    - name: Save AsciiDoc step
      uses: actions/upload-artifact@v1
      with:
        name: Output-document
        path: public/test.html