name: CICD-Manual
on:
  push:
    branches:
      - main

jobs:
  asciidoctor_job:
    runs-on: self-hosted
    name: Build AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build AsciiDoc step
      id: documents
      uses: Analog-inc/asciidoctor-action@master
      with:
        shellcommand: "asciidoctor release-manual/test.adoc -o public/test.html" 
    - name: Save AsciiDoc step
      uses: actions/upload-artifact@v1
      with:
        name: Output-document
        path: public/test.html